services:
  postgres:
    image: postgres:15-alpine
    container_name: aprobaciones-db
    environment:
      POSTGRES_DB: aprobaciones_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aprobaciones-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d aprobaciones_db"]
      interval: 5s       
      timeout: 3s        
      retries: 5         
      start_period: 10s

  # Opcional: PgAdmin para ver la BD visualmente
  pgadmin:
    image: dpage/pgadmin4
    container_name: aprobaciones-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - aprobaciones-network

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: dockerfile
  #   container_name: aprobaciones-backend
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USERNAME: admin
  #     DB_PASSWORD: admin123
  #     DB_DATABASE: aprobaciones_db
  #     PORT: 3000
  #     NODE_ENV: production
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - aprobaciones-network
  #   restart: unless-stopped

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: aprobaciones-frontend
  #   ports:
  #     - "4200:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - aprobaciones-network
  #   restart: unless-stopped
    
volumes:
  postgres_data:

networks:
  aprobaciones-network:
    driver: bridge